# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'spip install mkdocs-material'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'mkdocs build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'mkdir -p ~/digitalgarden'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'digitalgarden-maggiolo-net'
    sourceFolder: './site'
    contents: '**'
    targetFolder: '~/digitalgarden'
    cleanTargetFolder: true
    cleanHiddenFilesInTarget: true
    readyTimeout: '20000'