# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: Bash@3
#   displayName: 'Install mkdocs-material'
#   inputs:
#     targetType: 'inline'
#     script: 'pip install mkdocs-material'

- task: Bash@3
  displayName: 'Install mkdocs-material[imaging] and dependencies'
  inputs:
    targetType: 'inline'
    script: 'pipx install "mkdocs-material[imaging]" --include-deps && sudo apt-get -y install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev'

- task: Bash@3
  displayName: 'Build site with mkdocs'
  inputs:
    targetType: 'inline'
    script: 'mkdocs build'

- task: SSH@0
  displayName: 'Create remote directory'
  inputs:
    sshEndpoint: 'digitalgarden-maggiolo-net'
    runOptions: 'commands'
    commands: 'mkdir -p ~/digitalgarden'
    readyTimeout: '20000'

- task: CopyFilesOverSSH@0
  displayName: 'Copy site files to remote server'
  inputs:
    sshEndpoint: 'digitalgarden-maggiolo-net'
    sourceFolder: './site'
    contents: '**'
    targetFolder: '~/digitalgarden'
    cleanTargetFolder: true
    cleanHiddenFilesInTarget: true
    readyTimeout: '20000'

- task: SSH@0
  displayName: 'Move files to web server directory'
  inputs:
    sshEndpoint: 'digitalgarden-maggiolo-net'
    runOptions: 'commands'
    commands: 'sudo cp -r ./digitalgarden/* /var/www/html/digitalgarden/site/'
    readyTimeout: '20000'