# Sources: 
# - https://jameswillett.dev/getting-started-with-material-for-mkdocs/

site_name: Giorgio's Digital Garden
site_url: https://digitalgarden.maggiolo.net
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      # primary: green
      # accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      # primary: blue
      # accent: deep orange
  features:
    - navigation.footer

extra:
  social:
    - icon: simple/github
      link: https://github.com/aramilialon
    - icon: simple/linkedin
      link: https://linkedin.com/in/giorgio-maggiolo

markdown_extensions:
  # Material Emoji support
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  