# Sources: 
# - https://jameswillett.dev/getting-started-with-material-for-mkdocs/
# - https://squidfunk.github.io/mkdocs-material/setup

site_name: Giorgio's Digital Garden
site_url: https://digitalgarden.maggiolo.net/
extra_css: ['assets/custom.css']
theme:
  name: material
  logo: assets/ctm_solo_logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      # primary: green
      # accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      # primary: blue
      # accent: deep orange
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.path


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aramilialon
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/giorgio-maggiolo
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/giorgio.maggiolo

plugins: 
  # - blog
  - meta
  - social

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: python/name:pymdownx.superfences.fence_code_format
  
copyright: Copyright &copy; 2025 Giorgio Maggiolo