# Sources: 
# - https://jameswillett.dev/getting-started-with-material-for-mkdocs/
# - https://squidfunk.github.io/mkdocs-material/setup

site_name: Giorgio's Digital Garden
site_url: https://digitalgarden.maggiolo.net/
extra_css: 
  - stylesheets/profile-picture.css
  - stylesheets/extras.css
theme:
  name: material
  custom_dir: overrides
  logo: assets/ctm_solo_logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/ctm_solo_logo.png
  icon:
    logo: assets/ctm_solo_logo.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - toc.integrate
    - content.code.copy


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aramilialon
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/giorgio-maggiolo
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/giorgio.maggiolo

  status:
    draft: Draft
    wip: Work in Progress
    done: Completed
  status_explanation:
    text: WUT
    url: digital-garden

plugins: 
  # - blog
  - meta
  - social
  - search

markdown_extensions:
  - attr_list
  - meta
  - md_in_html
  - pymdownx.blocks.caption
  # Syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  
  # Content tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Diagrams
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: python/name:pymdownx.superfences.fence_code_format
  
copyright: Copyright &copy; 2025 Giorgio Maggiolo